services:
  - type: web
    name: our-world-private
    env: python
    buildCommand: "pip install -r requirements.txt || true"
    startCommand: "python server.py"
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: OURWORLD_PASSWORD
        sync: false
